// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMOpT3K53P50cFAA4vrT9KmwQBc4PACk',
    appId: '1:486404013987:web:ee28fdbb5f9e2037916416',
    messagingSenderId: '486404013987',
    projectId: 'skiddoapp',
    authDomain: 'skiddoapp.firebaseapp.com',
    storageBucket: 'skiddoapp.appspot.com',
    measurementId: 'G-KZDYNHXVB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-6BnZffEvwfKB-L05ncjnyryTTCKswCc',
    appId: '1:486404013987:android:40b679b2ebaa23fd916416',
    messagingSenderId: '486404013987',
    projectId: 'skiddoapp',
    storageBucket: 'skiddoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_UGVjZFLrRK9Rgc2QlEqvZM-U-a3N54Q',
    appId: '1:486404013987:ios:8ca9cc116d4f7e99916416',
    messagingSenderId: '486404013987',
    projectId: 'skiddoapp',
    storageBucket: 'skiddoapp.appspot.com',
    androidClientId: '486404013987-vqouvugv06fciggg658sjofp8qnnkqod.apps.googleusercontent.com',
    iosBundleId: 'com.example.skidooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_UGVjZFLrRK9Rgc2QlEqvZM-U-a3N54Q',
    appId: '1:486404013987:ios:4d2d5ead7c938224916416',
    messagingSenderId: '486404013987',
    projectId: 'skiddoapp',
    storageBucket: 'skiddoapp.appspot.com',
    androidClientId: '486404013987-vqouvugv06fciggg658sjofp8qnnkqod.apps.googleusercontent.com',
    iosBundleId: 'com.example.skidooApp.RunnerTests',
  );
}
